#ifndef common_h
#define common_h

/*
   uncomment these lines to allow debugging and printing of
   generated bytecodes
 */
// #define DEBUG_PRINT_CODE
// #define DEBUG_TRACE_EXECUTION

#define UINT8_COUNT (UINT8_MAX + 1)

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#endif