name: Cross-Platform Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: linux
            setup: sudo apt-get update && sudo apt-get install -y build-essential
          - os: windows-latest
            artifact_name: windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up build environment (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: ${{ matrix.setup }}
        shell: bash

      - name: Set up MSYS2 (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            base-devel
          update: true

      - name: Create build directories
        run: mkdir -p build/release
        shell: bash

      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Source files:"
          find . -name "*.c"
        shell: bash

      - name: Build project (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          gcc --version
          which gcc
          make

      - name: Build project (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: make
        shell: bash

      - name: List build output (Debug)
        run: |
          echo "Build directory contents:"
          ls -la build/release/
        shell: bash

      - name: Archive build artifacts (Unix-like)
        if: matrix.os != 'windows-latest'
        run: tar -czvf release-${{ matrix.artifact_name }}.tar.gz ./build/release/
        shell: bash

      - name: Archive build artifacts (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Compress-Archive -Path "build/release/*" -DestinationPath "release-${{ matrix.artifact_name }}.zip"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-artifact
          path: release-${{ matrix.artifact_name }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}

  release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*-artifact/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
