name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Debug directory structure
        run: ls -R

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: make

      - name: Archive build artifacts
        run: tar -czvf release-linux.tar.gz ./build/release/

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifact
          path: release-linux.tar.gz

  release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-artifact
          path: linux

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release of the build for Linux.
          draft: false
          prerelease: false

      - name: Upload Linux release asset
        uses: actions/upload-artifact@v4
        with:
          path: ./linux/release-linux.tar.gz
          compression-level: 9
          if-no-files-found: ignore
